### ISSUE TITLE
Authentication option in VoicemailMain

### ISSUE THREAD

**Issue by theHellDog** [adhearsion/adhearsion-asterisk#10]
In voicemail_main authentication option doesn't sends into AGI properly.
With
`voicemail_main(:mailbox => 500, :authenticate => false)`
we have in adhearsion log
`… :command=>"EXEC VoiceMailMain \"500\" \"s\""}, …`
and in asterisk log
`[Dec 14 11:45:27]     -- AGI Script Executing Application: (RINGING) Options: ()
[Dec 14 11:45:27]     -- AGI Script Executing Application: (VoiceMailMain) Options: (500)`

Temporarily i solved this by
`execute 'VoiceMailMain', '500,s'`

**Comment by benlangfeld** [comment]
Thanks for reporting this. Fix coming momentarily.
