### ISSUE TITLE
Code is an undefined method

### ISSUE THREAD

**Issue by lpradovera** [adhearsion/adhearsion-asterisk#6]
https://github.com/adhearsion/adhearsion-asterisk/blob/develop/lib/adhearsion/asterisk/call_controller_methods.rb#L22

This line is throwing an error every time it is invoked because #code is not defined on the complete event.

**Comment by benlangfeld** [comment]
Logs please. Also check Punchblock and Adhearsion-asterisk from develop :)

**Comment by benlangfeld** [comment]
Fixed in 4a54af0b95c829e50e29d6b95c63046f31287383. @polysics Can you please do a release?
